// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // マイグレーションには直接接続が必要。
    // DATABASE_URL は ?pgbouncer=true 付きの接続プール URL のため DDL を実行できない。
    // DIRECT_URL はプールを経由しない直接接続なので migrate dev/deploy で使う。
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
